---
title: "RHW2023_Nathan_Laroy"
author: "Nathan Laroy"
date: "2023-10-20"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T)
knitr::knit_hooks$set(inline = function(x) {
  x <- sprintf("%1.2f", x)
  paste(x, collapse = ", ")
  })
```

## R Markdown

## Question 1
```{r results = "hide"}
(HairEye <- apply(HairEyeColor, c(1, 2), sum))
(ClassSurvived <- apply(Titanic, c(1, 4), sum))
```

## Question 2
```{r results = "hide"}
# rows order
# > row_rank_order_indices <- sort(rowSums(HairEye), index.return = T, decreasing = T)$ix

# cols order
# > col_rank_order_indices <- sort(colSums(HairEye), index.return = T, decreasing = T)$ix

# re-ordered matrix
# > (HairEye_ordered <- HairEye[c(row_rank_order_indices), c(col_rank_order_indices)])

# all in one
(HairEye_ordered <- HairEye[c( sort(rowSums(HairEye), index.return = T, decreasing = T)$ix ),
                            c( sort(colSums(HairEye), index.return = T, decreasing = T)$ix )
                            ])
```

## Question 3
```{r results = "hide"}
(replace(HairEye, list = c(1:16), rank(HairEye)))
```

## Question 4
```{r results = "hide"}
(c( max( HairEye["Brown", ] ),
    max( HairEye["Blond", ] ), 
    max( HairEye[, "Blue"][ HairEye[, "Blue"] != max( HairEye[, "Blue"] ) ])
    ))
```

## Question 5
```{r }
# patched package 'kableExtra' required from devtools::install_github("kupietz/kableExtra")
#> In my R installation, rmarkdown produces error with regular "kableExtra" package when knitting, 
#> specifically for kable_classic() function.
#> This function extends kable() for "prettier" output, i.e. to obtain the one shown in assignment 5.
#> 
#> Code below tries to use kableExtra (if installed) (maybe it produces no error on other installations),
#> and prints regular kable() output when kable_classic() yields error, or when "kableExtra"
#> is not installed.

library(reshape2)
try(library(kableExtra), silent = T)

HairEye_longform <- melt(HairEye, id = c("Hair", "Eye"))
kable_object <- kable(HairEye_longform, col.names = c("Hair", "Eye", "Freq"), format = "html")
output <- try(kable_classic(kable_object, full_width = F), silent = T)

if (output == "try-error"){
  kable_object
} else {
  output
}

```

## Question 6
```{r results = "hide"}
all2x2 <- vector(mode = "list", length = length(HairEye))
list_position <- 1
for (i in 1:dim(HairEye)[1]){
  for (j in 1:dim(HairEye)[2]){
    value <- HairEye[i, j]
    row_sum <- sum(HairEye[i, ][HairEye[i, ] != HairEye[i, j]])
    col_sum <- sum(HairEye[, j][HairEye[, j] != HairEye[i, j]])
    rest_sum <- sum(HairEye[-i, -j])
    
    new_matrix <- matrix(c(value, col_sum, row_sum, rest_sum),
                         nrow = 2,
                         ncol = 2)
    
    all2x2[[list_position]] <- new_matrix
    list_position <- list_position + 1
  }
}
all2x2
```

## Question 7
```{r results = "hide"}
library(microbenchmark)

# Matrices with sums obtained via novel function and lapply()
#> 'x' is individual value from HairEye-like object, as needed for lapply();
#> 'data' is complete matrix, allows any HairEye- or ClassSurvived-like
#>        matrix object to be fed as needed for Q10;

matrix_of_sums <- function(x, data){
  
  dim_pos <- which(data == x, arr.ind = T)
  
  row <- dim_pos[1]
  col <- dim_pos[2]
  
  value <- data[row, col]
  row_sum <- sum(data[row, ][data[row, ] != data[row, col]])
  col_sum <- sum(data[, col][data[, col] != data[row, col]])
  rest_sum <- sum(data[-row, -col])
  
  (new_matrix <- matrix(c(value, col_sum, row_sum, rest_sum),
                         nrow = 2,
                         ncol = 2))
}

matrix_list <- lapply(HairEye, matrix_of_sums, data = HairEye)


# compare running times
forloop_times <- microbenchmark({
          all2x2 <- vector(mode = "list", length = length(HairEye))
          list_position <- 1
          for (i in 1:dim(HairEye)[1]){
            for (j in 1:dim(HairEye)[2]){
              value <- HairEye[i, j]
              row_sum <- sum(HairEye[i, ][HairEye[i, ] != HairEye[i, j]])
              col_sum <- sum(HairEye[, j][HairEye[, j] != HairEye[i, j]])
              rest_sum <- sum(HairEye[-i, -j])
              
              new_matrix <- matrix(c(value, col_sum, row_sum, rest_sum),
                                   nrow = 2,
                                   ncol = 2)
              
              all2x2[[list_position]] <- new_matrix
              list_position <- list_position + 1
            }
          }
          all2x2
                }, unit = "microseconds")
forloop_mean <- summary(forloop_times)["mean"]

lapply_times <- microbenchmark({lapply(HairEye, matrix_of_sums, data = HairEye)}, unit = "microseconds")
lapply_mean <- summary(lapply_times)["mean"]
```
The average time of the first computation is `r summary(forloop_times)[["mean"]]` microseconds and the average time of the second computation is `r summary(lapply_times)[["mean"]]` microseconds.

## Question 8
```{r results = "hide"}
calcOR <- function(x){
  (OR <- (x[1, 1] * x[2, 2])/(x[2,1] * x[1, 2]))
}

GlobalOddsRatio <- function(x){
  if (!is.matrix(x)){
    stop("is.matrix(x) is not TRUE")
  } else {
    matrix_list <- lapply(x, matrix_of_sums, data = x)
    odds_ratios <- lapply(matrix_list, calcOR)
    
    (replace(x, list = c(1:length(x)), unlist(odds_ratios)))
  }
}

ORs <- GlobalOddsRatio(HairEye)
```

## Question 9

```{r results = "hide"}
LogOddsRatio <- function(x, base = exp(1), adjust = 0.5){
  
    if (!is.matrix(x)){
    stop("is.matrix(x) is not TRUE")
  } else {
    # Formal args put through from LogOddsRatio()
    adjust_var <- adjust
    base_var <- base
    
    # New function calclogOR() like calcOR() from previous Q
    # Inherits formal args as stated above
    calclogOR <- function(x, base = base_var, adjust = adjust_var){
      x[which(x == 0)] <- 0 + adjust
      OR <- (x[1, 1] * x[2, 2])/(x[2,1] * x[1, 2])
      logOR <- log(OR, base = base)
    }
    
    # Calculate matrix of sums
    matrix_list <- lapply(x, matrix_of_sums, data = x)
    
    # output log ORs of matrices in matrix_list
    log_odds_ratios <- lapply(matrix_list, calclogOR)
    (replace(x, list = c(1:length(x)), unlist(log_odds_ratios)))
  }
}

logORs <- LogOddsRatio(HairEye)
```

## Question 10
```{r results = "hide"}
CreateTwoWay <- function(x){
  class(x) <- "TwoWay" ; x
}

GOR.TwoWay <- GlobalOddsRatio
LOR.TwoWay <- LogOddsRatio

GOR <- function(x, ...){
  UseMethod("GOR")
}
LOR <- function(x, ...){
  UseMethod("LOR")
}
```

```{r }
Titanic2Way <- CreateTwoWay(ClassSurvived)
class(Titanic2Way)
```

```{r eval = F}
GOR(Titanic2Way)
```
```{r echo = F}
# Without [,] at end, output includes class attribute on separate line
GOR(Titanic2Way)[,]
```

```{r eval = F}
LOR(Titanic2Way)
```
```{r echo = F}
# Without [,] at end, output includes class attribute on separate line
LOR(Titanic2Way)[,]
```